# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employ', '0003_auto_20160710_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='job_profile',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
