# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employ', '0007_auto_20160713_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
