# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('skill_set', models.CharField(max_length=500)),
                ('preferred_time', models.CharField(choices=[('MOR', 'MORNING'), ('AFT', 'AFTERNOON'), ('EVE', 'EVENING'), ('NIGHT', 'NIGHT'), ('ANY', 'ANYTIME')], max_length=3)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('emailID', models.EmailField(max_length=254)),
                ('qualifications', models.CharField(choices=[('MET', '10th pass'), ('INT', '12th pass'), ('U_G', 'Under Grdauate'), ('P_G', 'Post Graduate'), ('NON', 'None')], max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('skill_set', models.CharField(max_length=500)),
                ('preferred_time', models.CharField(choices=[('MOR', 'MORNING'), ('AFT', 'AFTERNOON'), ('EVE', 'EVENING'), ('NIGHT', 'NIGHT'), ('ANY', 'ANYTIME')], max_length=3)),
                ('contact_number', models.IntegerField(max_length=10)),
                ('emailID', models.EmailField(max_length=254)),
                ('qualifications', models.CharField(choices=[('MET', '10th pass'), ('INT', '12th pass'), ('U_G', 'Under Grdauate'), ('P_G', 'Post Graduate'), ('NON', 'None')], max_length=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
